// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.mixin.Maskable', {
  showLoadMaskOnMe: true,
  loadingMaskDelay: null,
  loadingMaskHideDelay: null,
  getLoadMaskTarget: function() {
    return this;
  }
});
