// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.mixin.ViewDragDrop', {
  commonBeforeDragOver: function(dropTo, e, id) {
    var recievablePaths, _ref, _ref1, _ref2;
    if (this.view === dropTo.view) {
      return true;
    }
    recievablePaths = ((_ref = dropTo.view.up('fieldcontainer')) != null ? (_ref1 = _ref.cache) != null ? (_ref2 = _ref1._myProperties) != null ? _ref2.recievablePaths : void 0 : void 0 : void 0) || [];
    if (-1 < recievablePaths.indexOf(this.view._uipath)) {
      return true;
    } else {
      return false;
    }
  }
});
