// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.view.DomainNavPanel', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.domainnavpanel',
  header: false,
  width: '100%',
  layout: {
    type: 'vbox',
    align: 'stretch'
  },
  items: [
    {
      xtype: 'filterToolBar',
      width: '100%',
      margin: '0 0 0 1'
    }, {
      xtype: 'filterCriteriaView',
      margin: '0 0 0 1'
    }, {
      flex: 1,
      xtype: 'domainTree',
      margin: '0 0 0 0'
    }
  ],
  listeners: {
    afterrender: function() {
      return this.down('domainTree').bindFilterStore(this.down('filterCriteriaView').getStore());
    }
  },
  constructor: function() {
    var su;
    su = Corefw.util.Startup;
    if (su.getThemeVersion() === 2) {
      this.ui = 'mainconfigui';
    }
    return this.callParent(arguments);
  }
});
