// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.util.Debug', {
  singleton: true,
  printOutGridFields: function() {
    return false;
  },
  printOutViews: function() {
    return false;
  },
  printOutRawResponse: function() {
    return false;
  },
  addDebugFunctions: function() {
    var startupObj, su;
    su = Corefw.util.Startup;
    startupObj = su.getStartupObj();
    if (startupObj && startupObj.debugMode) {
      return Ext.StoreManager.list = function() {
        return Ext.StoreManager.each(function(store) {
          return console.log(store.getCount(), store.storeId);
        });
      };
    }
  }
});
