// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.view.form.Fieldset', {
  extend: 'Ext.form.FieldSet',
  mixins: ['Corefw.mixin.FieldContainer'],
  xtype: 'corefieldset',
  style: {
    margin: '0 0 0 0',
    padding: '0px 0px 0px 0px'
  },
  listeners: {
    afterlayout: function() {
      var _ref;
      if (this.resizeWhenVisible) {
        if ((_ref = this.layoutManager) != null) {
          if (typeof _ref.resize === "function") {
            _ref.resize();
          }
        }
        delete this.resizeWhenVisible;
      }
    }
  },
  initComponent: function() {
    var layout, me, props, _ref;
    me = this;
    layout = Corefw.view.layout.Layout;
    me.layoutManager = layout.create(me);
    props = ((_ref = me.cache) != null ? _ref._myProperties : void 0) || {};
    if (props.title) {
      this.title = props.title;
    }
    me.uipath = props.uipath;
    me.callParent(arguments);
    me.disableFormEvents = true;
    me.layoutMain();
    me.renderTooltips();
    Corefw.util.Data.displayFormData(this, me.cache);
    me.disableFormEvents = false;
  },
  onResize: function() {
    this.layoutManager.resize(this);
  },
  loadRecord: function(record) {
    var data, me;
    Ext.suspendLayouts();
    data = record.getData();
    me = this;
    Ext.Object.each(data, function(fName, fVal) {
      var fObj;
      fObj = me.child("[name=" + fName + "]");
      if (fObj && fObj.setValue) {
        return fObj.setValue(fVal);
      }
    });
    Ext.resumeLayouts(true);
  }
});
