// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.model.PivotConfigItem', {
  extend: 'Ext.data.Model',
  fields: [
    {
      name: 'name',
      type: 'string'
    }, {
      name: 'path',
      type: 'string'
    }, {
      name: 'measure',
      type: 'boolean'
    }, {
      name: 'aggregate',
      type: 'boolean',
      defaultValue: false
    }, {
      name: 'sortby',
      type: 'string',
      defaultValue: "ASC"
    }
  ],
  idProperty: 'path',
  copyFrom: function(record, keyMapping) {
    if (keyMapping == null) {
      keyMapping = {};
    }
    return this.fields.each(function(field) {
      var key, targetKey;
      key = field.name;
      targetKey = keyMapping[key] ? keyMapping[key] : key;
      if (record.get(targetKey)) {
        return this.set(key, record.get(targetKey));
      }
    }, this);
  }
});
