// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.view.grid.LinkColumn', {
  extend: 'Ext.grid.column.Column',
  xtype: 'corelinkcolumn',
  initComponent: function() {
    if (this.disptype === 'ICON') {
      this.minWidth = this.maxWidth = this.text.length * 9 > 24 ? this.text.length * 9 : 24;
    }
    return this.callParent(arguments);
  },
  renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
    var column;
    column = metaData.column;
    if (column) {
      metaData.tdCls = column.disptype === 'ICON' ? column.labelMap[value] : ' linkcolumn';
    }
    return value;
  },
  afterRender: function() {
    var evt, props;
    evt = Corefw.util.Event;
    props = this.cache._myProperties;
    evt.addEvents(props, 'column', props);
  }
});
