// Generated by CoffeeScript 1.8.0
Ext.define("Corefw.view.form.field.CheckboxGroupField", {
  extend: "Ext.form.CheckboxGroup",
  mixins: ['Corefw.mixin.CoreField'],
  xtype: 'corecheckboxgroup',
  coretype: 'field',
  generatePostData: function() {
    var cache, fieldObj, name, props, val;
    cache = this.cache;
    props = cache._myProperties;
    name = props.name;
    val = this.getValue()[name];
    if (Ext.isEmpty(val)) {
      fieldObj = {
        name: name,
        value: []
      };
      return fieldObj;
    }
    if (!Ext.isArray(val)) {
      val = [val];
    }
    fieldObj = {
      name: name,
      value: val !== void 0 && val !== null ? val : []
    };
    return fieldObj;
  }
});
