// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.view.form.field.GridItemWarningMessage', {
  xtype: 'coregriditemwarningmessage',
  constructor: function(config) {
    var extCSSPrefix, fieldWarningCls, me, ownerEl, ownerField, tooltip;
    me = this;
    extCSSPrefix = Ext.baseCSSPrefix;
    fieldWarningCls = extCSSPrefix + 'form-warning-field';
    ownerField = config.field;
    ownerEl = ownerField.inputEl;
    ownerEl.addCls(fieldWarningCls);
    ownerField.on('change', function(field) {
      me.clearMessage();
    });
    tooltip = Ext.create('Ext.tip.ToolTip', {
      ui: 'tooltip-warning',
      target: ownerEl,
      renderTo: Ext.getBody()
    });
    this.showMessage = function(message) {
      var ownerElPosition;
      ownerEl.addCls(fieldWarningCls);
      tooltip.enable();
      tooltip.update(message);
      if (ownerEl) {
        ownerElPosition = ownerEl.getXY();
        ownerElPosition[1] = ownerElPosition[1] + ownerEl.getHeight() + 2;
        tooltip.showAt(ownerElPosition);
      }
    };
    this.clearMessage = function() {
      ownerEl.removeCls(fieldWarningCls);
      tooltip.disable();
    };
  }
});
