// Generated by CoffeeScript 1.8.0
Ext.define("Corefw.view.form.field.IconField", {
  extend: "Ext.form.FieldContainer",
  mixins: ['Corefw.mixin.CoreField'],
  xtype: 'coreiconfield',
  coretype: 'field',
  layout: 'hbox',
  initComponent: function() {
    var buttonConfig, props, textfieldConfig;
    props = this.cache._myProperties;
    textfieldConfig = {
      xtype: 'textfield',
      flex: 1
    };
    buttonConfig = {
      xtype: 'button',
      width: 30,
      iconCls: props.iconStyle,
      margin: '0 0 0 6',
      style: {
        'background-color': '#fff',
        border: 0
      }
    };
    this.items = [textfieldConfig, buttonConfig];
    if (props.value) {
      textfieldConfig.value = props.value;
    }
    this.callParent(arguments);
  },
  updateByCache: function(cache) {
    var button, field, iconCls, props;
    props = cache._myProperties;
    field = this.down('textfield');
    field.setValue(props.value);
    button = this.down('button');
    iconCls = props.iconStyle;
    button.iconCls !== iconCls && button.setIconCls(iconCls);
  },
  getPostValue: function() {
    var textfield;
    textfield = this.down('textfield');
    return textfield.getValue();
  },
  generatePostData: function() {
    var fieldObj;
    fieldObj = {
      name: this.name,
      value: this.getPostValue()
    };
    return fieldObj;
  }
});
