// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.view.form.field.LinkField', {
  extend: 'Ext.form.field.Display',
  mixins: ['Corefw.mixin.CoreField'],
  xtype: 'corelinkfield',
  protocolMap: {
    TELEPHONE: 'tel:',
    MAIL: 'mailto:'
  },
  initComponent: function() {
    var me, props, _ref;
    me = this;
    props = ((_ref = me.cache) != null ? _ref._myProperties : void 0) || {};
    me.pt = me.protocolMap[props.pseudoProtocol];
    me.callParent(arguments);
  },
  afterRender: function() {
    var me;
    me = this;
    me.inputEl.addListener('click', function(ev, el) {
      return me.fireEvent('linkclick', me);
    });
  },
  valueToRaw: function(val) {
    var pt;
    if (val) {
      pt = this.pt;
      val = pt ? "<a href='" + pt + val + "'>" + val + "</a>" : "<a href='javascript:;'>" + val + "</a>";
    }
    return val;
  },
  rawToValue: function(rawVal) {
    if (rawVal) {
      rawVal = rawVal.replace(/<\s*(\S+)(\s[^>]*)?>/g, '');
    }
    return rawVal;
  }
});
