// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.view.form.field.RadioGroupField', {
  extend: 'Ext.form.RadioGroup',
  mixins: ['Corefw.mixin.CoreField'],
  xtype: 'coreradiogroup',
  coretype: 'field',
  listeners: {
    boxready: function(comp) {
      var radio, radioWidth, span;
      radio = comp.el.query('input[type=button]')[0];
      radioWidth = radio.offsetWidth;
      span = document.createElement('span');
      document.body.appendChild(span);
      comp.el.query('.x-form-radio-group').forEach(function(ct) {
        var label, labels, maxText, text, _i, _len;
        maxText = '';
        labels = ct.querySelectorAll('input+label');
        for (_i = 0, _len = labels.length; _i < _len; _i++) {
          label = labels[_i];
          text = label.innerText;
          text.length > maxText.length && (maxText = text);
        }
        span.innerText = maxText;
        return ct.style.minWidth = radioWidth + span.offsetWidth + 20 + 'px';
      });
      return document.body.removeChild(span);
    }
  },
  generatePostData: function() {
    var fieldObj, name, val;
    val = this.getValue() || {};
    name = this.name;
    fieldObj = {
      name: name,
      value: val[name] !== void 0 && val[name] !== null ? val[name] : ''
    };
    return fieldObj;
  }
});
