// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.view.form.field.TextAreaField', {
  extend: 'Ext.form.field.TextArea',
  mixins: ['Corefw.mixin.CoreField'],
  xtype: 'coretextarea',
  setValue: function(value) {
    var theValue;
    if (Ext.isObject(value) && value.displayValue) {
      theValue = value.value;
      this.valueType = Ext.typeOf(theValue);
      arguments[0] = theValue;
    }
    return this.callParent(arguments);
  },
  getValue: function() {
    var value, valueType;
    value = this.callParent(arguments);
    if (valueType = this.valueType) {
      switch (valueType) {
        case 'number':
          value = +value;
          break;
        case 'boolean':
          value = value === 'false' ? false : true;
      }
    }
    return value;
  },
  afterRender: function() {
    var borderLess, _ref, _ref1, _ref2, _ref3;
    if (((_ref = this.cache) != null ? (_ref1 = _ref._myProperties) != null ? _ref1.editable : void 0 : void 0) === false) {
      this.setReadOnly(true);
    }
    if (borderLess = (_ref2 = this.cache) != null ? (_ref3 = _ref2._myProperties) != null ? _ref3.borderless : void 0 : void 0) {
      this.inputEl.setStyle('border', 'none');
      return this.inputEl.setStyle('background-image', 'none');
    }
  }
});
