// Generated by CoffeeScript 1.8.0
Ext.define('Corefw.view.ntf.Notification', {
  extend: 'Ext.Component',
  xtype: 'corenotification',
  componentCls: 'cv-notification',
  listeners: {
    afterrender: function(me) {
      var animateWithOpacity, el, initAutoClose, initCloseClickEvent;
      el = me.el;
      animateWithOpacity = function() {
        el.animate({
          duration: 500,
          from: {
            opacity: 0
          },
          to: {
            opacity: 1
          }
        });
      };
      initAutoClose = function() {
        var timeout, timeoutIndicator, _ref, _ref1;
        timeoutIndicator = el.down('.cv-notification-timeout-indicator');
        timeout = (_ref = me.cache) != null ? (_ref1 = _ref._myProperties) != null ? _ref1.timeout : void 0 : void 0;
        if (!timeout) {
          return;
        }
        timeoutIndicator.animate({
          duration: timeout * 1000,
          from: {
            width: '0%'
          },
          to: {
            width: '100%'
          },
          listeners: {
            afteranimate: function() {
              me.destroy();
            }
          }
        });
      };
      initCloseClickEvent = function() {
        var closeEl;
        closeEl = el.down('.cv-notification-close');
        closeEl.on('click', function() {
          el.animate({
            duration: 200,
            from: {
              opacity: 1
            },
            to: {
              opacity: 0
            },
            listeners: {
              afteranimate: function() {
                me.destroy();
              }
            }
          });
        });
      };
      animateWithOpacity();
      initAutoClose();
      initCloseClickEvent();
    }
  },
  tpl: new Ext.Template(["<div class='cv-notification-body'>", "<div class='cv-notification-icon cv-notification-icon-{messageType}'></div>", "<div class='cv-notification-title'>", "{title}", "</div>", "<div class='cv-notification-msg'>", "{message}", "</div>", "<span class='cv-notification-close'>×</span>", "</div>", "<div class='cv-notification-timeout-indicator'></div>"])
});
